[package]
name = "dir-example"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
glob = "0.3.1"
same-file = "1.0.6"
walkdir = "2.5.0"

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
