[package]
name = "ansi_terminal"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
