[package]
name = "encoding_complex"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
byteorder = "1.4.3"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
toml = "0.5.9"

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
