[package]
name = "text_regex"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
lazy_static = "1.5.0"
regex = "1.11.0"
stringreader = "0.1.1"

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
