[package]
name = "encoding_csv"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
anyhow = "1.0.68"
csv = "1.1.6"
serde = { version = "1.0.152", features = ["derive"] }

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
