[package]
name = "encoding_csv"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
anyhow = "1.0.89"
csv = "1.3.0"
serde = { version = "1.0.210", features = ["derive"] }

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
