[package]
name = "sqlite-example"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
anyhow = "1.0.68"
rusqlite = "0.28.0"

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
