[package]
name = "string_parsing"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
unicode-segmentation = "1.10.1"

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
