[package]
name = "encoding_string"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
base64 = "0.20.0"
data-encoding = "2.3.3"
percent-encoding = "2.2.0"
url = "2.3.1"

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
