[package]
name = "encoding_string"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
base64 = "0.13.0"
data-encoding = "2.3.2"
percent-encoding = "2.1.0"
url = "2.2.2"

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
