[package]
name = "encoding_string"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
base64 = "0.20.0"
data-encoding = "2.6.0"
percent-encoding = "2.3.1"
url = "2.5.2"

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
