[package]
name = "debugging_tracing"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
cookbook_utils = { path = "../../../cookbook_utils" }
