[package]
name = "parallel"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
glob = "0.3.1"
image = "0.24.9"
rand = "0.8.5"
rayon = "1.10.0"

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
