[package]
name = "hashing"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
ring = "0.16.20"
data-encoding = "2.6.0"

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
