[package]
name = "hashing"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
data-encoding = "2.3.2"
ring = "0.16.20"

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
