[package]
name = "parallel"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
glob = "0.3.0"
image = "0.24.2"
rand = "0.8.5"
rayon = "1.5.3"

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
