[package]
name = "tar_archive"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
flate2 = "1.0.34"
tar = "0.4.42"

[dev-dependencies]
cookbook_utils = { path = "../../cookbook_utils" }
